added Quest Trigger EXEC
Hartie95/Grasscutter pull request #23
Opened 2022-10-28 04:48 UTC by mjolsic

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
 - added EXEC_ADD_CUR_AVATAR_ENERGY
 - added EXEC_CHANGE_AVATAR_ELEMET
 - added new function 'changeAvatarElement' in player.java
 - changed hardcoded MC depot skill to read json data in HandlerSetPlayerBornDataReq.Data
 - changed refill function in EnergyManager.java
 

## Type of changes

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

2022-10-28 11:12 UTC, Hartie95 requested changes

2022-10-28 11:12 UTC, Hartie95 commented on src/main/java/emu/grasscutter/game/player/Player.java
> +        if (mainCharacter.getData().getCandSkillDepotIds() == null){
Might be good to also check the bounds here, to prevent an out of bounds read on the array with a wrong value.

2022-10-28 16:01 UTC, mjolsic commented
Resolved changes requested in commit [5ed739583bf01ad9c48379f33e78dc2984d55bff]

2022-10-29 04:14 UTC, Hartie95 approved these changes

2022-10-29 04:16 UTC, merged